cc_library(
    name = "sqf-lang",
    hdrs = ["sqf_type.h", "sqf_command.h", "nullary_keywords.h", "unary_keywords.h", "binary_keywords.h", "all_keywords.h"],
    visibility = ["//src/lexer:__pkg__", "//src/analyzer:__pkg__"],
)