// Convenience file to include all the AST node types
#include "./array.h"
#include "./assign.h"
#include "./ast.h"
#include "./binary_op.h"
#include "./code.h"
#include "./compound.h"
#include "./no_op.h"
#include "./nullary_op.h"
#include "./number.h"
#include "./string_literal.h"
#include "./unary_op.h"
#include "./variable.h"
