// Convenience file to include all the AST node types
#include "src/ast/ast.h"
#include "src/ast/array.h"
#include "src/ast/assign.h"
#include "src/ast/binary_op.h"
#include "src/ast/code.h"
#include "src/ast/compound.h"
#include "src/ast/no_op.h"
#include "src/ast/nullary_op.h"
#include "src/ast/number.h"
#include "src/ast/string_literal.h"
#include "src/ast/unary_op.h"
#include "src/ast/variable.h"