cc_library(
    name = "sqf-errors",
    hdrs = ["error_type.h", "error_messages.h", "error.h"],
    deps = ["//src/lexer:sqf-tokens"],
    visibility = ["//src/lexer:__pkg__", "//src/parser:__pkg__", "//src/analyzer:__pkg__"],
)