cc_library(
    name = "sqf-parser",
    srcs = ["parser.cpp"],
    hdrs = ["parser.h"],
    deps = ["//src/lexer:sqf-lexer", "//src/ast:abstract-syntax-tree"],
    visibility = ["//src/tester:__pkg__"],
)