cc_library(
    name = "sqf-analyzer",
    srcs = ["analyzer.cpp"],
    hdrs = ["analyzer.h"],
    deps = ["//src/parser:sqf-parser", "//src/errors:sqf-errors"],
    visibility = ["//src/main:__pkg__"],
)