cc_library(
    name = "sqf-analyzer",
    srcs = ["analyzer.cpp"],
    hdrs = ["analyzer.h"],
    deps = ["//src/sqf:sqf-lang", "//src/parser:sqf-parser"],
    visibility = ["//src/main:__pkg__", "//test:__pkg__"],
)