cc_library(
    name = "sqf-analyzer",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = ["//src/parser:sqf-parser"],
    visibility = ["//src/rules:__pkg__", "//test/analyzer:__pkg__"],
)
