cc_library(
    name = "sqf-preprocessor",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = ["//src/errors:sqf-errors"],
    visibility = ["//src/lexer:__pkg__", "//test/preprocessor:__pkg__"],
)
